#!/usr/bin/env bash
#
# Requirements: rg (ripgrep)
# Author: James Cherti
# URL: https://github.com/jamescherti/bash-stdops
#
# Description:
# ------------
# Recursively search the specified directory and print the list of file paths to
# standard output. By default, it ignores:
#   - `.git` directories,
#   - files that match `.gitignore` rules,
#   - and binary files.
#
# License:
# --------
# Copyright (C) 2012-2024 James Cherti
#
# Distributed under terms of the GNU General Public License version 3.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -euf -o pipefail

if [[ $# -ne 1 ]]; then
  echo "Recursively search the specified directory and print the list of file "
  echo "paths."
  echo "(By default, it ignores '.git' directories, files matching "
  echo "'.gitignore' rules. When rg is used, it also ignores binary files.)"
  echo
  echo "Usage: $0 <dir>" >&2
  echo
  exit 1
fi

DIR="$1"
if ! [[ -d "$DIR" ]]; then
  echo "Error: The specified directory does not exist: $DIR" >&2
  exit 1
fi

if type -P rg &>/dev/null; then
  RG_CMD=(rg --hidden --no-messages --color=never --no-heading --files)
  RG_CMD+=(--glob '!.git')
  RG_CMD+=(--glob '!.svn')
  RG_CMD+=("--" "$DIR")
  exec "${RG_CMD[@]}"
elif type -P fd &>/dev/null; then
  # TODO: add filter for binary files
  RG_CMD=(fd --hidden --color=never)
  exec "${RG_CMD[@]}"
elif type -P grep &>/dev/null; then
  # TODO: add filter for binary files
  RG_CMD=(grep --color=auto --exclude-dir=.git --exclude-dir=.svn)
  exec "${RG_CMD[@]}"
else
  echo "Error: One of the following commands is required: rg, fd, or grep" >&2
  exit 1
fi
