#!/usr/bin/env bash
#
# Requirements:
#   - pbpaste (on macOS)
#   - xclip (for X11 environments)
#   - sed
#
# Author: James Cherti
# URL: https://github.com/jamescherti/bash-stdops
#
# Description:
# ------------
# The pbpaste command-line utility that reads the contents of the system
# clipboard and writes it to standard output (stdout). This allows users to
# access clipboard contents within scripts, the terminal, or other command-line
# tools.
#
# This script pastes content from the clipboard. It adapts based on the
# environment:
# - If running on macOS with pbpaste, it uses pbpaste.
# - If running in an X11 environment with xclip, it uses xclip to access the
#   clipboard.
#
# Usage:
#   cbpaste
#
# License:
# --------
# Copyright (C) 2012-2026 James Cherti
#
# Distributed under terms of the GNU General Public License version 3.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -euf -o pipefail

paste_from_xclip() {
  xclip -o -selection clipboard || return 1
}

remove_newline() {
  if [[ "${CBPASTE_STRIP_NEWLINE:-}" -eq 0 ]]; then
    cat
  else
    sed -z "s/\\n\+$//"
  fi
}

main() {
  # macOS
  if type -P pbpaste &>/dev/null; then
    exec pbpaste
  fi

  # Source bash-stdops library
  local script_dir
  script_dir="$(dirname "${BASH_SOURCE[0]}")"
  # shellcheck disable=SC1091
  source "$script_dir/.bash-stdops.inc.sh"

  # Paste
  local errno=0
  if is_wayland && type -P wl-paste &>/dev/null; then
    wl-paste --no-newline || errno=1
  elif { is_x11 || is_wayland; } && type -P xclip &>/dev/null; then
    paste_from_xclip | remove_newline 2>/dev/null || errno=1
  fi

  exit "$errno"
}

main
