#!/bin/bash
#
# Requirements:
#   - xclip
#
# Author: James Cherti
# URL: https://github.com/jamescherti/bash-stdops
#
# Description:
# ------------
# Monitor the clipboard and display its content when it changes.
#
# License:
# --------
# Copyright (C) 2012-2024 James Cherti
#
# Distributed under terms of the GNU General Public License version 3.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Check the clipboard after LOOP_INTERVAL seconds
LOOP_INTERVAL=0.25

clipboard_paste() {
  # Function to paste text from a clipboard
  local clipboard_name="$1"
  xclip -selection "$clipboard_name" -o 2>/dev/null || true
}

watch_clipboard() {
  # Function to monitor a clipboard.
  local clipboard_name="$1"
  local previous=""

  local current
  while true; do
    current=$(clipboard_paste "$clipboard_name")

    if [[ "$current" != "$previous" ]]; then
      previous="$current"
      echo "$clipboard_name: $current"
    fi

    sleep "$LOOP_INTERVAL"
  done
}

watch_clipboard "clipboard"
