#!/usr/bin/env bash
#
# Requirements:
#   - git
#
# Author: James Cherti
# URL: https://github.com/jamescherti/bash-stdops
#
# Description:
# ------------
# This script recursively locates all Git repositories starting from a specified
# directory or the current directory if none is provided.
#
# It first checks for fd to perform faster searches; if unavailable, it
# defaults to find.
#
# The script outputs the paths of all discovered Git repositories to standard
# output.
#
# License:
# --------
# Copyright (C) 2012-2025 James Cherti
#
# Distributed under terms of the GNU General Public License version 3.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -euo pipefail

main() {
  local base_dir
  if [[ $# -gt 0 ]]; then
    base_dir="$1"
  else
    base_dir="."
  fi

  local dot_git_dirs
  if command -v fd &>/dev/null; then
    mapfile -t dot_git_dirs < <(fd --type d --hidden --no-ignore-vcs \
      --no-ignore-parent '^\.git$' "$base_dir")
  else
    mapfile -t dot_git_dirs < <(find "$base_dir" -type d -name .git)
  fi

  local item
  local repo_dir
  for item in "${dot_git_dirs[@]}"; do
    repo_dir=$(dirname "$item")
    echo "$repo_dir"
  done
}

main "$@"
