#!/usr/bin/env bash
#
# Requirements:
#   - git
#
# Author: James Cherti
# URL: https://github.com/jamescherti/bash-stdops
#
# Description:
# ------------
# The git-is-pushed script checks if all local commits have been pushed to that
# remote. Exits with status 1 if there are unpushed commits or if no upstream
# branch is configured.
#
# License:
# --------
# Copyright (C) 2012-2026 James Cherti
#
# Distributed under terms of the GNU General Public License version 3.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -u
set -e

TARGET_DIR=$(realpath "${1:-.}")

# Check if the current branch has a tracking remote branch configured
if ! git -C "$TARGET_DIR" rev-parse --abbrev-ref '@{u}' >/dev/null 2>&1; then
  echo "Error: $TARGET_DIR: The current branch has no remote upstream branch." >&2
  exit 1
fi

# Check for commits that exist locally but have not been pushed to the upstream branch
UNPUSHED=$(git -C "$TARGET_DIR" rev-list '@{u}..HEAD')
if [[ -n "$UNPUSHED" ]]; then
  echo "Error: $TARGET_DIR: Unpushed commits detected." >&2
  exit 1
fi
