ifeq ($(PREFIX),)
	PREFIX=/usr/local
endif

all:
	@echo "System-side installation:"
	@echo "    sudo make install"
	@echo ""
	@echo "Alternative: Install in your home directory:"
	@echo "    PREFIX=~/.local make install"
	@echo ""

install:
	install -d "$(PREFIX)/bin"
	install -m 755 ./autoperm "$(PREFIX)/bin/"
	install -m 755 ./path-lowercase "$(PREFIX)/bin/"
	install -m 755 ./path-tr "$(PREFIX)/bin/"
	install -m 755 ./path-uppercase "$(PREFIX)/bin/"
	install -m 755 ./path-is "$(PREFIX)/bin/"
	install -m 755 ./qparallel "$(PREFIX)/bin/"
	install -m 755 ./rgfiles "$(PREFIX)/bin/"
	install -m 755 ./rgfiles-run "$(PREFIX)/bin/"
	install -m 755 ./rgfiles-sre "$(PREFIX)/bin/"
	install -m 755 ./sre "$(PREFIX)/bin/"
	install -m 755 ./git-sre "$(PREFIX)/bin/"
	install -m 755 ./git-squash "$(PREFIX)/bin/"
	install -m 755 ./git-dcommit "$(PREFIX)/bin/"
	install -m 755 ./sshwait "$(PREFIX)/bin/"
	install -m 755 ./cbcopy "$(PREFIX)/bin/"
	install -m 755 ./cbpaste "$(PREFIX)/bin/"
	install -m 755 ./tmux-cbpaste "$(PREFIX)/bin/"
	install -m 755 ./tmux-run "$(PREFIX)/bin/"
	install -m 755 ./tmux-session "$(PREFIX)/bin/"
	install -m 755 ./largs "$(PREFIX)/bin/"

uninstall:
	rm "$(PREFIX)/bin/autoperm"
	rm "$(PREFIX)/bin/path-lowercase"
	rm "$(PREFIX)/bin/path-tr"
	rm "$(PREFIX)/bin/path-uppercase"
	rm "$(PREFIX)/bin/path-is"
	rm "$(PREFIX)/bin/qparallel"
	rm "$(PREFIX)/bin/rgfiles"
	rm "$(PREFIX)/bin/rgfiles-run"
	rm "$(PREFIX)/bin/rgfiles-sre"
	rm "$(PREFIX)/bin/sre"
	rm "$(PREFIX)/bin/git-sre"
	rm "$(PREFIX)/bin/git-squash"
	rm "$(PREFIX)/bin/git-dcommit"
	rm "$(PREFIX)/bin/sshwait"
	rm "$(PREFIX)/bin/cbcopy"
	rm "$(PREFIX)/bin/cbpaste"
	rm "$(PREFIX)/bin/tmux-cbpaste"
	rm "$(PREFIX)/bin/tmux-run"
	rm "$(PREFIX)/bin/tmux-session"
	rm "$(PREFIX)/bin/largs"
