#!/usr/bin/env bash
#
# Requirements:
#   - notify-send (optional)
#
# Author: James Cherti
# URL: https://github.com/jamescherti/bash-stdops
#
# Description:
# ------------
# This program simply displays a notification. It can be used in the terminal
# while another command is running. Once the command finishes executing, a
# notification is displayed, informing the user that the process has completed.
#
# License:
# --------
# Copyright (C) 2012-2026 James Cherti
#
# Distributed under terms of the GNU General Public License version 3.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -euf -o pipefail

if type -P notify-send >/dev/null 2>&1; then
  notify-send --urgency=critical "[TASK OVER] $*" || true
fi

echo "========================================================================="
echo " [TASK OVER] $*"
echo "========================================================================="
