#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/bash-stdops
#
# Description:
# ------------
# This script processes a given file path, extracts the directory and filename,
# converts the filename to lowercase.
#
# Example usage:
#   path-lowercase /Path/TO/FILE
#   This will convert the filename to lowercase, producing: /Path/TO/file
#
# License:
# --------
# Copyright (C) 2012-2026 James Cherti
#
# Distributed under terms of the GNU General Public License version 3.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -euf -o pipefail

if [[ $# -lt 1 ]]; then
  echo "Convert filenames to lowercase."
  echo
  echo "Usage: $0 <path-to-file>"
  echo
  exit 1
fi

exec path-tr "$1" '[:upper:]' '[:lower:]'
