#!/bin/bash
#
# Requirements:
#   - tmux
#
# Author: James Cherti
# URL: https://github.com/jamescherti/bash-stdops
#
# Description:
# ------------
# This script attempts to attach to an existing `tmux` session. If the session
# does not exist, it creates a new session with that name.
#
# If no session name is provided, it defaults to creating or attaching to a
# session named "0".
#
# Usage:
#   tmux-run <session-name>
#
# License:
# --------
# Copyright (C) 2012-2025 James Cherti
#
# Distributed under terms of the GNU General Public License version 3.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -euf -o pipefail

TMUX_SESSION_LOOP=0
TMUX_SESSION_NAME="0"

show_usage() {
  echo "Usage: $0 [-h]" >&2
  echo
  echo "-h    Show this help message and exit"
  echo "-l    Restart the tmux session after it quits"
  exit 1
}

while getopts ":hl" opt; do
  case ${opt} in
  l)
    TMUX_SESSION_LOOP=1
    ;;
  h)
    show_usage
    ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    exit 1
    ;;
  :)
    echo "Invalid option: -$OPTARG requires an argument" >&2
    exit 1
    ;;
  esac
done
shift $((OPTIND - 1))

open-tmux-session() {
  if ! tmux -2 attach-session -t "$TMUX_SESSION_NAME"; then
    tmux -2 new -s "$TMUX_SESSION_NAME"
  fi
}

main() {
  if [[ $# -gt 0 ]]; then
    TMUX_SESSION_NAME="$1"
  fi

  if [[ $TMUX_SESSION_LOOP -ne 0 ]]; then
    while true; do
      open-tmux-session
      echo "Restarting the Tmux session '$TMUX_SESSION_NAME'..."
      sleep 1
    done
  else
    open-tmux-session
  fi
}

main "$@"
